### ISSUE TITLE
Out Parameters TPFLSH

### ISSUE THREAD

**Issue by AndFab** [usnistgov/REFPROP-issues#260] opened 2020-02-28 07:56 UTC
### Description
Hi, 

I have a question regarding the subroutine TPFLSHdll. In the REFPROP Documentation
Release 10.0 it says that the compositions of the vapor phase and the liquid phase can either be returned as arrays of mole fractions or mass fractions. The overall composition is supposed to be in mole fractions so what I'm wondering is how i know or determine what type of fraction that is returned? 

![Subroutine TPFLSHdll](https://user-images.githubusercontent.com/61552716/75521307-bd92b200-5a07-11ea-81b5-1d3dc665c03e.png)

**Comment by ianhbell** [comment] 2020-02-28 15:05
I think the problem is the documentation; in this function, all inputs are molar fractions

**Comment by EricLemmon** [comment] 2020-04-06 21:18
Only the very top level routines (REFPROP, ALLPROPS, and ABFLSH) allow the user to set the input and output units.  The lower level routines are always molar based.  In versions 9.1 and before, these "lower" level routines were at that time the top level routines, and they did not include any unit conversions.  With Refprop 10, those routines were all demoted and the three listed above replaced all others.  That meant that we reduced the number of routines necessary to obtain all options that a user might need from 150 down to three!  And technically down to just one, the REFPROP routine, which calls the other two.  This one routine does the work of all the others so that the user only has to learn the inputs and outputs to it, and not to the other 150 (which also were not always consistent).  In addition it also includes the ability to use molar or mass units, both for properties and for compositions, and returns many other things that were not available in the 150 routines in 9.1.  It is a big jump forward to ease the burden of the user in learning the code.

Concerning your question and Ian's comment, there are a few places in the manual with some mistakes in it.  Those have been fixed in the Fortran code.  Ian has set up an automatic method to extract the information from the Fortran code in order to produce the manual at any time so that we do not have two sets of documentation to change simultaneously.

**Closed as completed** 2020-04-29 03:02 UTC
Labels: document update
