### ISSUE TITLE
Excel Add-In won't run on new computer

### ISSUE THREAD

**Issue by lindarobinson** [usnistgov/REFPROP-issues#14] opened 2018-04-27 21:54 UTC
Hello. I'm a frequent user of the RERPROP excel add-in. I have recently upgraded my computer and I cannot get the add-in to work on my new computer. I have followed all the instructions (and tried all the tips) on the README.md file. The add-in is functioning well enough that the REFPROP functions are available in excel, but the only result I get to my inputs are the error result "#VALUE!"

Both my previous computer and my new computer run Windows 10; however my previous computer had Excel 2013 and my new computer has Excel 2016.

I obtained the REFPROP program through purchase of TKSolver by UTS, which includes REFPROP. The standalone REFPROP program is functioning just fine on the new computer, it is just the excel add-in that I am struggling with.

**Comment by ianhbell** [comment] 2018-04-27 21:57
My suspicion is that your new Excel is 64-bit and the old Excel was 32-bit.  If so, you need to run the 9.1.1 patch and you should be in business: http://trc.nist.gov/refprop/911/REFPROP.HTM (it installs a 64-bit DLL).  If this fixes your issue, please close this issue in the web interface.

**Comment by lindarobinson** [comment] 2018-04-27 22:05
I've checked the Excel version on both machines (File>Account>About Excel) and am seeing that both the new and the old are 32-bit versions. I'm assuming that means I should not run the patch you suggested.

**Comment by ianhbell** [comment] 2018-04-28 15:39
I'll do my best to help, but technically, you will have to contact the vendor for technical support.  We only officially support purchase through NIST SRD.

**Comment by ianhbell** [comment] 2018-04-28 15:40
What inputs did you try that result in #VALUE! ?

**Comment by ianhbell** [comment] 2018-04-28 15:41
Actually, I bet it is an issue with the Intel runtimes.  If you run the patch I linked above, it might fix that (9.1.1 statically links the Intel runtimes)

**Comment by lindarobinson** [comment] 2018-04-30 13:52
I appreciate the support and understand the issue with having purchased the REFPROP software as a part of the TK Solver package. I am dubious they will provide me any support with the excel add-in. If it is necessary I will just repurchase the software through NIST SRD. At this point I have so many models that use the add-in I need to get it running.

I did try the patch and did not notice any change. The inputs I am using to test if it is working is:
=density("water","tp","e",62,14.7)

I also notice that even when I open the add-in file (REFPROP.xls) I get the #VALUE! result for the listing of the DLL version on the Examples tab (and in many many other cells.) Perhaps this is informative about the issue. I've attempted to attach a screen shot to show you what I mean. 

![capture](https://user-images.githubusercontent.com/38797821/39430583-d5665cba-4c53-11e8-9c26-ab17cacc67d2.PNG)

**Comment by ianhbell** [comment] 2018-04-30 14:43
In that case, I suspect the culprit is that the installation directory is not on the PATH environment variable.  Adding it to the PATH should fix this problem I think. 

Better question: where _is_ REFPROP.dll installed in your case?

**Comment by lindarobinson** [comment] 2018-04-30 15:49
REFPROP.dll is saved in this directory: 

C:\Program Files (x86)\UTS\TK Solver 5.0\TKExtLib

That is the directory that REFPROP was installed in when I installed the TKSolver software. The fluids and mixtures folders are in there as well, and also the REPROP.xlam files that I link to for the add-in. This is the exact setup that I have on my previous computer that works. Nevertheless, per your suggestion, I just added C:\Program Files (x86)\UTS\TK Solver 5.0\TKExtLib  as a path variable on my new computer but it is still not working. 

Would it help if I create a folder C:\Program Files (x86)\REFPROP and copy all the files to there?

**Comment by ianhbell** [comment] 2018-04-30 16:02
Yeah, that is a good idea to try; but what I had in mind was to add C:\Program Files (x86)\UTS\TK Solver 5.0\TKExtLib to the PATH environment variable.  E.g.: https://www.java.com/en/download/help/path.xml

**Comment by lindarobinson** [comment] 2018-04-30 16:14
I added it; nothing changed.

**Comment by lindarobinson** [comment] 2018-04-30 16:50
I tried both of those and when I open the REFPROP.xls file now I also get teh #VALUE! result for the Name of this File field (i.e. cell C4.) See below.

![image](https://user-images.githubusercontent.com/38797821/39439105-17303a04-4c6c-11e8-96c2-b98a46d3d8f1.png)

**Comment by ibell** [comment] 2018-04-30 17:33
Can you also move the excel addin into one of the c:\Program Files folders? And make sure that Excel is loading from that addin?

**Comment by lindarobinson** [comment] 2018-04-30 18:36
I had already moved the excel addin file into the  c:\Program Files\REFPROP folder, but I had not revised the Add-in path in Excel. 

I have now done that and the result is that it now correctly gets the file path in the "Name of this file" field (cell C4), but all the other cells still have #VALUE! as the result. Basically, it now looks like the first screen shot I shared.

**Comment by ibell** [comment] 2018-05-02 22:54
I talked with my colleague and he recommended that you email him to get
access to REFPROP 10 beta, which has fixed a lot of Excel-related problems:
eric.lemmon .at. nist.gov

**Comment by lindarobinson** [comment] 2018-05-07 15:10
I got a copy of REFPROP 10 and am basically having the same exact issue. I can install the Add-ins and they appear to be active, but the calculations won't work. Not even the one that should report on what the DLL Version is.

I installed REFPROP 10 on my previous computer and I was able to get it working within minutes. So it is definitely something specific to my new computer. The only significant difference I am aware of between the set-up on the machines is that the new computer is running Excel 2016 and the old computer is running Excel 2013.

**Comment by Christophercombo** [comment] 2018-06-13 17:59
Do you think you can repost that link to the 9.1.1 patch? Unlike the author, I was switching over from a 32-bit to 64-bit installation of office and am encountering issues with all my old spreadsheets that were integrated with refprop.

Thank you!

Chris

**Comment by ianhbell** [comment] 2018-06-13 18:05
Can you please email me at ian.bell@nist.gov and I'll send you the URL?

**Comment by Nobuo-Okita** [comment] 2018-09-25 06:11
I have downloaded REFPROP v10 and recently chenged the version of excel from 2010 to 2016. After the update, the old excel files besed on 2010 office with REFPROP v10 add-in have not done well with "#NAME?". Both excels of 2010 and 2016 are 32bits.

**Comment by lindarobinson** [comment] 2018-09-25 13:57
Despite support from the folks at REPROP, I was never able to get the REPROP plug in to work with excel 2016. My solution was to replace with excel 2013.

**Comment by jgunderson1** [comment] 2018-11-16 23:55
Thanks Eric. We have indeed had issues with machines running Excel 2016. I will email you directly and if we are able to make progress on what the issue is, perhaps we can drop an update into this thread.

**Comment by ianhbell** [comment] 2018-11-17 08:02
Can you please keep the conversation on github?  Perhaps in a new thread?  That way others can learn from your correspondence (and so can google)

**Comment by jgunderson1** [comment] 2018-11-17 17:18
Ian, thanks for the reply. Our engineers and IT folks will work directly with Eric to troubleshoot this, but once we understand the problem and (hopefully) the solution, I agree it is important to document the results here in this thread or a new one depending on what seems most appropriate. We will be doing screen share as part of the troubleshooting and possibly discussing company-specific information, so I would prefer to come back here later and provide a summary rather than try to put all of the communication here as we go along.

**Comment by AJ-Slippey** [comment] 2019-01-14 14:51
I am having a similar problem having just gotten a new work computer and my add-in is no longer working. Has anything been resolved with this in the past two months?

**Comment by ibell** [comment] 2019-01-14 16:59
How did you install the addin on your new computer?

**Comment by AJ-Slippey** [comment] 2019-01-14 19:00
I have the .dll files along with the REFPROP.xlam file and the folders of fluid and mixture properties in C:/REFPROP. From Excel, I select that .xlam file as an add-in. I have also followed the advice about setting up the trust center settings from this older video: https://www.youtube.com/watch?v=wxwp_7WIYQQ 
Similar to the OP, I have the functions available, but just get "#VALUE!" for everything. Also, similarly, it appears to be related to a move from Excel 2010 to Excel 2016.

**Comment by jgunderson1** [comment] 2019-01-14 21:57
Ian and Eric, 

I am suddenly aware that I forgot to update this thread when our situation was resolved. It turned out after some investigation that our issue was not a problem with Excel 2016, but rather a more common issue with paths that we were able to work out on our own. At some point in our recent software upgrades, a script responsible for setting path variables stopped working. After correcting this, REFPROP was fully functional. We certainly appreciate your help and I'm sorry for the false alarm.

**Comment by AJ-Slippey** [comment] 2019-01-29 18:18
I'll not rule it out, but I've been unable to locate any path errors and I continue to have the same problem as previously described. Any other suggestions out there?

**Comment by wjmorris** [comment] 2019-02-03 02:11
I'm having the exact same problem as originally described by @lindarobinson. Company upgraded our machines and now my REFPROP Excel sheets don't work (although the program itself runs fine). Running Windows 10 Pro, Excel 2016 x64, and REFPROP 9.1. I've also tried just about every suggestion I've come across. Uninstalled & reinstalled, modified my Windows path variables, the VB macro... Nothing works. I'll be emailing a request to @ianhbell for that patch URL. Will update y'all with the results. Just wanted to chime in and make clear that this does NOT seem to be an isolated problem.

**Comment by wjmorris** [comment] 2019-02-04 18:33
Looks like that's what I'll have to do for now. Obviously it'd be preferable to use the tools I already spent hours developing though. I do appreciate your support @ianhbell and @EricLemmon. Hopefully we can resolve this soon

**Comment by EricLemmon** [comment] 2019-02-05 01:02
I've found another machine that I should be able to log into and try to work this out (which I'll do on Wednesday).  If we figure it out, I'll post the solution right away.

**Comment by EricLemmon** [comment] 2019-02-06 23:59
I was able to log onto a machine this morning and resolved the problem, at least with that machine.  I have been putting together a list of items that I learned while fixing the problem.  I've also opened up a new thread because this one is getting rather long, and hopefully not needed any more.  The new thread is here:

https://github.com/usnistgov/REFPROP-issues/issues/105

Please do not post anything else to this thread here (#14), but rather #105.

**Closed** 2019-02-06 23:59 UTC
Labels: help wanted
