### ISSUE TITLE
Compressbility calculation using GERG for Gulf gas Coast composition

### ISSUE THREAD

**Issue by devastromadhan** [usnistgov/REFPROP-issues#325] opened 2020-08-10 10:49 UTC
Hi Everyone,
I am very new to refprop, am trying to calculate the compressibility factor using GERG.

The calculation works fine for the predefined Mixture files(ex. Gulf coast gsa composition - GLFCOAST.mix).
When i execute THERM2 or ALLPROPS or REFPROP subroutine after executing SETMIXTURE, the calculation is working fine.
When the SETMIXTURE is not executed, there is a slight difference in the output.
In my case, the gas composition is dynamic, so gas composition cannot be predefined and want to do the calculation without .mix files.
Can you please help me with setting up the mixture without the .mix file?

Please find the below subroutine calls and please correct me if am wrong.
1. Setup refprop path 
	SETPATH
		hpath - C:\Program Files (x86)\REFPROP
2. Enable GERG 
	FLAGS 
		hFlag - GERG  //Enable GERG
		jFlag - 1	  // 1 to enable GERG
		kFlag - 0 	  // after execution, kFlag = 1
3. Run setup 
	SETUP
		numcomps - 20 //number of components 20 
		hFld - methane|nitrogen|Carbon dioxide|ethane|propane|isobutan|butane|ipentane|pentane|hexane|heptane|octane|nonane|decane|hydrogen|oxygen|CO|H2S|helium|argon
		hFmix - hmx.bnc,
		hrf - DEF,
4. Calculate Spline 
	SATSPLN
		z - 0.965222,0.002595,0.005956,0.018186,0.004596,0.000977,0.001007,0.000473,0.000324,0.000664,0,0,0,0,0,0,0,0,0,0 //from Gulf Coast mixture
5. Calculate Density as function of Temperature & Pressure 
	TPFLSH
		Temperature - 250 K
		Pressure - 7556.02 kPa
		z - 0.965222,0.002595,0.005956,0.018186,0.004596,0.000977,0.001007,0.000473,0.000324,0.000664,0,0,0,0,0,0,0,0,0,0 //from Gulf Coast mixture
6. Calculate compressibility factor 
	ALLPROPS
		hOut - "FPV,Z"
		iUnits - "-1"
		iMass - 0
		iFlag - 0 
		Temperature - 250 K
		Density - output from the above step // 4.9999979561525043
		z - 0.965222,0.002595,0.005956,0.018186,0.004596,0.000977,0.001007,0.000473,0.000324,0.000664,0,0,0,0,0,0,0,0,0,0 //from Gulf Coast mixture
	calculated compressibility factor = 0.72702373294869749,
	but the expected compressibility factor(From REFPROP HMI & AGA8.xls) = 0.72702333654292028

It is working fine When i execute the subroutine SETMIXTURE with mixture file(GLFCOAST.mix) before step 4.

**Expected behavior:** Compressibility factor = 0.72702333654292028

**Actual behavior:** Compressibility Factor = 0.72702373294869749

### Versions

**REFPROP Version:** 10 
**Operating System and Version:** Win 10 
**Access Method:** using C# wrapper

Thanks in Advance.

**Comment by ianhbell** [comment] 2020-08-10 13:54
I suspect the issue here is the universal gas constant, as the values for R for each component are not the same, and REFPROP offers a few options for how to deal with that for mixtures.  I will check your example on my side to see if I can confirm this behavior.  Have you tried with the high-level REFPROP functiion?

**Comment by ianhbell** [comment] 2020-08-10 14:21
I think I get the same answer, from two different approaches:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

# molar composition
z = [0.965222,0.002595,0.005956,0.018186,0.004596,0.000977,0.001007,0.000473,0.000324,0.000664,0,0,0,0,0,0,0,0,0,0] # from Gulf Coast mixture
# fluid string
hfld = 'methane|nitrogen|Carbon dioxide|ethane|propane|isobutan|butane|ipentane|pentane|hexane|heptane|octane|nonane|decane|hydrogen|oxygen|CO|H2S|helium|argon'
root = 'C:/Program Files (x86)/REFPROP'

RP = REFPROPFunctionLibrary(root)
RP.FLAGSdll('GERG', 1)
RP.SETUPdll(20, hfld, 'HMX.BNC','DEF')
RP.SATSPLNdll(z)
T, p = 250, 7556.02
print(RP.TPFLSHdll(T, p, z))
r = RP.REFPROPdll(hfld.replace('|','*'), 'TP','D;Z;R', RP.MOLAR_BASE_SI, 0, 0, T, p*1e3, z)
print(r.Output[0:3])
```
yielding
```
TPFLSHdlloutput(D=4.999997956152497, Dl=4.999997956152497, Dv=4.999997956152497, x=array('d', [0.965222, 0.002595, 0.005956, 0.018186, 0.004596, 0.000977, 0.001007, 0.000473, 0.000324, 0.000664, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [0.965222, 0.002595, 0.005956, 0.018186, 0.004596, 0.000977, 0.001007, 0.000473, 0.000324, 0.000664, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=999.0, e=-5260.207298872747, h=-3749.0026811383905, s=-46.34542660196874, Cv=29.500080088474135, Cp=60.003601901255436, w=366.880349926094, ierr=0, herr='')
array('d', [4999.997956152497, 0.7270237329486979, 8.314472])
```

**Comment by ianhbell** [comment] 2020-08-10 14:23
As you can see in my example (in the future, please provide a similar sort of example), the gas constant is 8.314472 J/mol/K and the compressibility factor is identical with your result. GERG mode seems to be enabled, and both the high-level routine of REFPROPdll and the low-level routine of TPFLSHdll both give the same density (one is in mol/L, the other in mol/m^3)

**Comment by devastromadhan** [comment] 2020-08-10 14:50
Hi @ianhbell ,
Thanks for the quick response.

I have tried high level REFPROP & low level routine of TPFLSH, both outputs the same compressibility factor, but the expected value is different(only up to 6 decimals it is same)

Expected behavior: Compressibility factor = 0.72702333654292028

Actual behavior: Compressibility Factor = 0.72702373294869749

Difference between actual & expected : 0.00000039640577709

For the same composition, with TPFLSH routine, if i set the mixture file using SETMIXTUREdll by specifying the mixture file "GLFCOAST.mix", it is giving the correct result.(**D = 5.0000006823759611, Z =  0.72702333654292028**). Before calling the TPFLSH routine, if you call the SETMIXTURE with mixture file name "GLFCOAST.mix", you can see the difference.

So, am not sure whether the issue is because of the gas constant or the mixture needs to be setup properly.

**Comment by ianhbell** [comment] 2020-08-10 15:15
There seems to be a bug in REFPROP when additional components are provided along with zero compositions.

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

root = 'C:/Program Files (x86)/REFPROP'

# Parameters to match entries in GLFCOAST.MIX
z = [0.965222,0.002595,0.005956,0.018186,0.004596,0.000977,0.001007,0.000473,0.000324,0.000664]
hfld = 'methane|nitrogen|Carbon dioxide|ethane|propane|isobutan|butane|ipentane|pentane|hexane'

RP = REFPROPFunctionLibrary(root)
RP.FLAGSdll('GERG', 1)

def do_calc(RP, z):
    T, p = 250, 7556.02
    RP.SATSPLNdll(z)
    r = RP.REFPROPdll('', 'TP','D;Z;R', RP.MOLAR_BASE_SI, 0, 0, T, p*1e3, z)
    print(r.Output[0:3])

RP.SETMIXTUREdll('GLFCOAST.MIX')
do_calc(RP, z)

RP.SETUPdll(20, hfld, 'HMX.BNC', 'DEF')
do_calc(RP, z)

# Add in the other zero placeholders to compositions and components (this gives a different answer; bug)
z += [0]*10 
hfld += '|heptane|octane|nonane|decane|hydrogen|oxygen|CO|H2S|helium|argon'
RP.SETUPdll(20, hfld, 'HMX.BNC', 'DEF')
do_calc(RP, z)
```
yields
```
array('d', [5000.000682375966, 0.72702333654292, 8.314472])
array('d', [5000.000682375966, 0.7270233365429202, 8.314472])
array('d', [4999.997956152497, 0.7270237329486976, 8.314472])
``` 
but all three outputs should be identical

**Comment by devastromadhan** [comment] 2020-08-11 09:45
Thanks @ianhbell 

It's working fine after removing the additional components with zero compositions.

**Comment by EricLemmon** [comment] 2020-08-16 01:01
This bug appears to have already been fixed in the latest code, however, I have the code all torn apart and not ready to make a new DLL.  If you would like one, please send me an email (eric.lemmon@nist.gov) and I'll send it to you once the code is back together.

**Closed as completed** 2020-08-23 07:50 UTC
Labels: bug, mixtures, Fortran code
