### ISSUE TITLE
erroneous k-values in Excel calculation

### ISSUE THREAD

**Issue by walterhw1950** [usnistgov/REFPROP-issues#48] opened 2018-09-06 19:48 UTC
### Description

When calculating a k-value for a component (mole fraction in vapor phase)/(mole fraction in liquid phase) using the Excel wrapper function returns a value of about 1.2 where a value of 1.0 is expected.  Admittedly this is for the case of component A in component A.  But still, the result should be 1.0.

### Steps to Reproduce

Paste the following into an Excel cell where REFPROP 10.0 is installed.  
"=1e-6/REFPROP("xmoleliq","R114;R114|1e-6;"&(1-1e-6),"PVAP","mks",101.3,1)"
or
"=REFPROP("xmolevap","R114;R114|1e-6;"&(1-1e-6),"PLIQ","mks",101.3,1)/1e-6"

**Expected behavior:** [What you expect to happen]

The expected k-value for 1ppm molar R114 in R114 is 1.0

**Actual behavior:** [What actually happens]

The value returned is 1.23472849417033

3. Change the component.  Similar non-1.0 values are returned.  
4. Change the composition to 50%molar as in the following
"=0.5/REFPROP("xmoleliq","R114;R114|0.5;"&(1-0.5),"PVAP","mks",101.3,1)"
and the value 1.0 is returned.  But this should happen for all values of component concentration

### Versions

**REFPROP Version:** 10.0  
**Operating System and Version:** Windows 7  
**Access Method:** Excel wrapper that came with 10.0

### Additional Information

Admittedly having the two components identical is a pathological situation, but does it indicate a problem with xmolevap or xmoleliq that would not show an obvious error when the two components are different?

**Comment by ianhbell** [comment] 2018-09-07 07:32
Good question!  So I'm not sure precisely what is going on in this case (maybe @EricLemmon has some idea?) but the formulation of our mixture model does not guarantee that the mixture properties are invariant when you split up a given component into two components of the same name with compositions adding up to the original.  So this is maybe a consequence of this behavior?

**Comment by EricLemmon** [comment] 2018-09-26 01:55
This happens because Refprop uses a prediction scheme to estimate the mixing parameters when the parameters have not been fitted and are not in the mixing file called HMX.BNC.  For this system it estimates a value of GammaT of 0.98847.  If you were to add the "mixture" R114/R114 to the HMX.BNC file and set the interaction parameters to 1, then the answers would be as expected.

**Comment by EricLemmon** [comment] 2018-10-21 05:30
Could you close this issue as well if we have answered your questions?

**Comment by walterhw** [comment] 2018-10-21 13:01
Thank you Eric,  
I suppose that the root of the issue is that the method used for estimating mixing parameters does not recognize the case for component A in component A.  I just wanted someone who knows more about it than I do to have a look.

**Closed as completed** 2018-10-21 13:06 UTC
Labels: documentation
