### ISSUE TITLE
Make ASHRAE Fundamental Refrigerant Plot with Refprop V10

### ISSUE THREAD

**Issue by brulegb** [usnistgov/REFPROP-issues#83] opened 2018-12-19 02:58 UTC
Hello,
I cannot figure out how to make Refprop V10 reproduce the plots in the ASHRAE Fundamental handbook, which were made with Refprop version 7

![image](https://user-images.githubusercontent.com/45960837/50196131-e1804100-02f6-11e9-9310-3e888bbb84c1.png)

**Comment by ianhbell** [comment] 2018-12-19 03:10
REFPROP’s *routines* were used to generate that figure in the ASHRAE handbook, but the generation of beautiful P-H plots like those are a major endeavor.  REFPROP’s GUI can generate p-h plots (Plot->p-h Diagram), but it won’t look precisely like that.  Other options for p-h plot generation that I know about are CoolPack (https://www.ipu.dk/products/coolpack/) and SmoWeb (http://platform.sysmoltd.com/ThermoFluids/FluidPropsCalculatorView?model=PHDiagram) but others exist too.

**Comment by EricLemmon** [comment] 2018-12-19 22:02
The GUI can be used to make something similar to the ASHRAE tables, except that the labels cannot be rotated.  Select a fluid and then go to Options/Reference State and change it to "ASHRAE".  To start making the plot, go to Plot/p-h Diagram, press the "More" button, and enter the extra density lines you would like to plot.  There are not enough spaces there to enter all of them from the ASHRAE plot, but we can make that happen with a little bit of extra work.  Note that I took off the option to add the units to the numbers.

![image](https://user-images.githubusercontent.com/42392984/50248242-910cf000-0397-11e9-9d44-7680abf136d1.png)

The plot will then be generated.  You can change the colors by going to Plot/Modify Plot, selecting all of the isotherms for example, and select a new color.

![image](https://user-images.githubusercontent.com/42392984/50248311-c87b9c80-0397-11e9-9bbc-4218dda74760.png)

You can also use that menu to change the line thickness.

I chose my density range to include as many as possible so that I had to enter less in the extra boxes that were available with the "More" button.  Go back to Plot/Modify Plot and select the ones that are not on the ASHRAE plot, and remove them.  You'll also have to delete their labels on the plot.

Go to File/Save and save the current session just in case you mess up later and need to reload it.

You can now change the label colors if you want, and add a unit or two to some of the numbers.  With a little bit of hacking, you could also edit the *.rfp file to do this quickly.  My plot now looks like the picture below.

![image](https://user-images.githubusercontent.com/42392984/50249615-bef43380-039b-11e9-846c-cbfcb7d776bb.png)

To get the extra densities, first go to Options/Properties and turn on Quality.  Then go to Calculate/Isoproperty Tables, click density on the left and pressure on the right, press Enter, and click on the options at the bottom.

![image](https://user-images.githubusercontent.com/42392984/50249698-fe228480-039b-11e9-807d-af543ee49b26.png)

Then enter 0.15 and press Enter.  Enter 0.1 and press Enter.  Continue down to 0.02, finally press ESC to exit that screen.  Save your session again (under a new name)!  You'll then need to delete all the 2-phase data points in the new table, those are the ones with quality less than 1.  Then go to Plot/Overlay and press Enter after the menu pops up.  This will add the new lines to the plot.  Then add labels for the new lines (Plot/Add Label), and move the labels to the correct position.  The final plot looks like the picture below (but first I went to Plot/Modify and turned on the Gridlines).

![image](https://user-images.githubusercontent.com/42392984/50250343-bb61ac00-039d-11e9-90b8-3b016556edbb.png)

**Comment by ianhbell** [comment] 2018-12-19 22:12
Wow, that’s great, thanks for putting this info together! Would it perhaps make sense to have the ability to do such nice pictures somewhat more automatically in REFPROP GUI?

**Comment by EricLemmon** [comment] 2018-12-19 22:34
As I wrote this up and made the graph, I definitely thought about that.  Here are some issues that came to mind:

1)  Add more boxes in the "More" section when making a new plot, or give the ability to read from a file all of the isolines that are desired.
2) Add the ability to not calculate 2-phase states when calculating isolines.
3) I cut off the plot at 200 Btu/lbm because the isochores exceeded the 460 K upper limit on my plot, it would be nice to have a cutoff point.
4) Add options in the initial setup of the plot that specifies the line color and thickness, along with label colors.
5) Use better logic to decide where to put the labels.
6) Add the ability to rotate the labels, or better to have the program rotate the labels automatically.

Having put these down gives me a reminder of what to do, and it will be interesting to see if other people request other options.

**Comment by brulegb** [comment] 2018-12-20 00:32
That was good, this example gave me more insight into Refprop.  I was able
to do it in about 1 hour. I am using the 245f to establish if I can make an
ORC that a bit more like the Stirling cycle.  The diagram is more for
presentation since the data for calculation are from an application
table exported from Refprop.  It would be nice if we could place points on
the plot by specifying two properties and have a line joining the points.

[image: image.png]
When setting up the colours, I save them in the Default but when I tried to
make a new plot, what I saved in the default did not follow.  Am I using
the default function incorrectly? I cannot figure out what it is for.

Thanks for the information.

**Comment by EricLemmon** [comment] 2018-12-21 02:37
Clicking the "Save as defaults" button in the Plot/Modify Plot window changes the colors, line thicknesses, etc. for situations where you are graphing data that you created in a table.  This does not work when selecting a pre-defined plot in the drop down Plot menu, but implementing option 4 that I mentioned above and being able to save those as defaults would allow this to work.

To place points on a plot, simply create a table (under the Calculate menu) containing the values you would like to plot, and then go to Plot/Overlay Plot.  You can then overlay those points on the plot in the format you would like.

One very interesting feature of the plots in Refprop is the ability to right click on the plot, which puts a small circle at this location.  The fun part depends on whether or not you have a Calculate/Specified State Points menu open.  Right clicking on the plot will place the values on the plot into the table, and will then calculate all other properties.  When you are finished right-clicking on the points you want, double click (left button) on the plot, and change the properties of the last item listed in the window so that a line connects the points.  The picture below shows this, including two state points where I right clicked points in the solid phase but it would not calculate those point (by design).

![image](https://user-images.githubusercontent.com/42392984/50321332-a2382880-048d-11e9-90c5-bc60e325947a.png)

**Closed as completed** 2019-01-30 19:48 UTC
Labels: question, feature-request, documentation, GUI
