### ISSUE TITLE
V10.0 & V9.1 have different thermal conductivity value (~2x)  for gas mixture?

### ISSUE THREAD

**Issue by victorlo1** [usnistgov/REFPROP-issues#376] opened 2021-01-19 21:23 UTC
When I calculate gas mixture (below) transport properties, using V9.1 & V.10.0, most properties agreed except thermal conductivity, which is different by 2x.
Can you fix that?
Thanks.

![mixture](https://user-images.githubusercontent.com/77699650/105094504-3acc7880-5a59-11eb-8037-b668bd710a1a.png)

![image](https://user-images.githubusercontent.com/77699650/105094539-4750d100-5a59-11eb-9eaa-9a99af1dca4f.png)

**Comment by ianhbell** [comment] 2021-01-19 22:15
Are those the screenshots you intended to add?  I see two times the compositions.  It would be helpful to see what inputs properties you put in.

**Comment by victorlo1** [comment] 2021-01-19 22:56
Yes, I have compositions twice because was not sure if the 1st one worked..

Below I show the thermal cond. calculated from 2 versions and they are different (see row 1 for both).

I also attached the mixture rfp file.

**Comment by ianhbell** [comment] 2021-01-19 22:58
Please be aware that responding to the issue via email the attachments don't attach.  You need to add the attachments online

**Comment by victorlo1** [comment] 2021-01-19 23:03
Below I show the thermal cond. calculated from 2 versions and they are different (see row 1 for both).

I also attached the mixture rfp file.

Thanks.
- Victor

 
![image](https://user-images.githubusercontent.com/77699650/105104579-635b6f00-5a67-11eb-9eb4-d04a7cbbe853.png)


![image](https://user-images.githubusercontent.com/77699650/105104585-6b1b1380-5a67-11eb-9294-9af5d6c534b1.png)

**Comment by ianhbell** [comment] 2021-01-20 02:51
Can you do your calculations in SI units as well to check whether it is unit conversion issue?

**Comment by nist-aharvey** [comment] 2021-01-20 03:11
I would also suggest trying it for each individual pure component at that condition.  It may be that something has changed with the reference correlation for just one of the components.
In general, it is much easier for us to diagnose a problem if it can be reduced to something simple, like a pure component calculation or at most a binary mixture.  There are too many variables if a bug report has many components.

**Comment by victorlo1** [comment] 2021-01-20 15:03
1. Yes, I have entered with SI unit and still got the same outcome.
2. Regarding to debugging with pure components, that is NIST job. I am just a user and reporting issues and bugs. I am sure you experts can do a much better job.

**Comment by ianhbell** [comment] 2021-01-20 15:29
1. Can you please show your example in SI units?
2. We are certainly a bit closer to the code itself, but to be able to debug thoroughly, we need to know exactly what inputs caused the trouble.

Did you get warnings when you set up this mixture in the GUI in either 9.1 or 10?

**Comment by victorlo1** [comment] 2021-01-20 15:56
Ian,
I think I found possibly another bug.....
I just tried another mixture (same constituents but diff compositions) in V9.1,
and this time I have different results between SI units and British units, mainly different  Cp. (i.e. 1.8 conversion factor is missing)

![image](https://user-images.githubusercontent.com/77699650/105200651-ed9de480-5af4-11eb-9467-c6db6978dd6b.png)

Yes, I have warning in the italic entry indicating its out of range and I will use data with cautions....
![image](https://user-images.githubusercontent.com/77699650/105200336-9730a600-5af4-11eb-9598-90eb597a294a.png)

I will post more if I have more info. Thanks.

**Comment by victorlo1** [comment] 2021-01-20 15:57
BTW, it is interesting the Pr number is same even Cp is wrong...

**Comment by ianhbell** [comment] 2021-01-20 15:59
Yes I noticed that too. Perhaps the issue is only the heading in the table?

**Comment by victorlo1** [comment] 2021-01-20 16:02
Ohh, you are right!! 
Cp unit is not truly SI with a R.
you have sHARP EYE.

**Comment by victorlo1** [comment] 2021-01-20 16:14
interesting that Cp use R, but conductivity use K......
Anyway, I think I learn my lesson....
i.e. Do not mix units..

**Comment by ianhbell** [comment] 2021-01-20 16:29
Yes, mixing units is a dangerous game.  Always either all SI or all English is the rule for me.

**Comment by victorlo1** [comment] 2021-01-20 17:45
Ian,
I went back to try the first mix, in both British & SI, in both V9.1 & V10.0
Both yeild same difference result in conductivity, so its not conversion issue.
Thanks.

![image](https://user-images.githubusercontent.com/77699650/105213618-c6024880-5b03-11eb-80d7-47c0136e29b8.png)

![image](https://user-images.githubusercontent.com/77699650/105213669-d4e8fb00-5b03-11eb-9d4a-f0e7cd690bca.png)

**Comment by ianhbell** [comment] 2021-01-20 17:48
That's "good", at least now we have a clear place to start debugging.  Looks like the density is slightly different as well suggesting a change to interaction parameters and/or flash calculation solution.  Where is this point relative to saturation?  Must be WAY supercritical, right?

**Comment by victorlo1** [comment] 2021-01-20 18:14
The 'Quality' is superheated, but do not know how much supercritical.

![image](https://user-images.githubusercontent.com/77699650/105217076-41fe8f80-5b08-11eb-8285-922310de8cbf.png)

**Comment by ianhbell** [comment] 2021-01-20 18:54
And REFPROP doesn't seem to want to calculate an isopleth of the phase envelope, which isn't a great sign

**Comment by ianhbell** [comment] 2021-01-20 18:54
Or possibly it doesn't have a critical point at this composition

**Comment by victorlo1** [comment] 2021-01-20 19:03
I know this mixture is stretching REFPROP capability and certainly I will use the calculated properties with caution.
but at least I expect similar results between 9.1 and 10.0. :)

**Comment by EricLemmon** [comment] 2021-02-10 07:03
I plotted the thermal conductivity at zero pressure (basically the dilute gas thermal conductivity) and came up with the plot shown below.  The red line contains calculations from Version 10 for the mixture, blue are those from Version 9.1, and all the others are the pure fluid values.  The uppermost line (in green) is for hydrogen.  The other four black lines are for the other pure fluids in the mixture.  

Hydrogen is only 5% of this mixture, so the correct mixture values should lie somewhere in the range of the other four fluids, although a bit higher than the average of the other four due to the large offset in the hydrogen calculations.  This appears to be the case for the red line.  Thus, it appears that version 9.1 did not calculate the thermal conductivity correctly for this mixture, and sometime between 9.1 and 10 this bug was fixed.

![image](https://user-images.githubusercontent.com/42392984/107475954-32380100-6b32-11eb-9eea-587eabbc3f13.png)

**Comment by EricLemmon** [comment] 2021-03-30 00:42
There's a lot to digest in this issue, and I'm not sure if there is still a problem in Version 10 with these calculations.  Can you please let us know?  If all is good, would you close this issue?

**Closed as completed** 2021-04-11 00:03 UTC
Labels: transport properties

**Comment by victorlo1** [comment] 2021-04-21 21:20
AEROJET ROCKETDYNE PROPRIETARY
Hi, Eric,
RP1 mix was in V9.1, but not in V10.0
Is it no longer supported?
Thanks.

-         Victor

**Comment by EricLemmon** [comment] 2021-04-22 04:13
Hi Victor,

I'll send you a private email with the necessary files.  RP1 has never been part of any release of Refprop, rather we send it out  separately when people ask for it.

Eric

**Comment by EricLemmon** [comment] 2021-04-22 04:16
I thought I had your email address, but I don't.  Can you send that to me at eric.lemmon@nist.gov?
