### ISSUE TITLE
LIMITS failure for transport properties of mixtures

### ISSUE THREAD

**Issue by vdiky** [usnistgov/REFPROP-issues#154] opened 2019-04-09 16:46 UTC
### Description

Calling LIMITS to check the availability of a transport model for a binary mixture returns false negative.

### Steps to Reproduce

Called from C++

```cpp
strcpy(htyp, "TCX");
double z[20];
for (int i=0; i<20; i++) z[i] = 0;
z[0] = z[1] = 0.5;
LIMITSdll (htyp, z, t1, t2, d2, p2, 3);
if (d2 > 0)
{
    //a model exists;
}
```

Sample mixture: R125 + R152a
**Expected behavior:** [What you expect to happen]

Expected non-zero d2

**Actual behavior:** [What actually happens]

d2 is 0

### Versions

Refprop.dll 10.0

**Comment by ianhbell** [comment] 2019-04-09 17:19
N.B.: I edited the code block to remove whitespace

In the future, can you please provide a runnable example, something that we can copy+paste and run?  That would therefore indicate to us what REFPROP function definitions you are using, what variable sizes you have employed, what types you are passing to the function, etc.  An error in any one of those pieces could easily throw off the internal calculations in REFPROP.

Also, it's a better idea to use ``std::vector<double> z(20,0.0)`` rather than ``double z[20]`` because the STL containers will do bounds checking

**Comment by vdiky** [comment] 2019-04-09 17:37
1. Can I pass vector<double> to refprop.dll?
2. Do you have a c++ project calling refprop.dll? If not, I'll share my sandbox where you can insert pieces.

**Comment by ianhbell** [comment] 2019-04-09 18:58
1. Not directly, but because ``std::vector<double>`` are guaranteed to be contiguous blocks of memory, you can pass the pointer to the first element, like so: ``&(z[0])`` in place of passing ``z``
2. Yes, please see https://github.com/CoolProp/REFPROP-headers

**Comment by ianhbell** [comment] 2019-04-09 20:32
I cannot reproduce this failure.  My code in Python:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\\Program Files (x86)\\REFPROP')
RP.SETPATHdll('D:\\Program Files (x86)\\REFPROP')
RP.SETFLUIDSdll('R125 * R152A')
z = [0.5,0.5] + [0.0]*18
r = RP.LIMITSdll('TCX', z)
print(r)
```
with the result
```
LIMITSdlloutput(Tmin=157.52104174627524, Tmax=500.16903317141134, Dmax=15.94324139402057, Pmax=60000.0)
```

**Comment by vdiky** [comment] 2019-04-10 00:40
You're right; it works for TCX in this case. It fails with ETA and STN for this particular mixture.

**Comment by ianhbell** [comment] 2019-04-10 15:47
ETA doesn't work because it should be VIS: (but the documentation needs to be fixed).  STN yields reasonable, though odd, values
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\\Program Files (x86)\\REFPROP')
RP.SETPATHdll('D:\\Program Files (x86)\\REFPROP')
RP.SETFLUIDSdll('R125 * R152A')
z = [0.5,0.5] + [0.0]*18
for k in ['TCX','VIS','STN']:
    r = RP.LIMITSdll(k, z)
    print(k, r)
```
yielding
```
TCX LIMITSdlloutput(Tmin=157.52104174627524, Tmax=500.16903317141134, Dmax=15.94324139402057, Pmax=60000.0)
VIS LIMITSdlloutput(Tmin=157.52104174627524, Tmax=500.16903317141134, Dmax=15.94324139402057, Pmax=60000.0)
STN LIMITSdlloutput(Tmin=1.0003380663428227, Tmax=362.91464776464534, Dmax=0.0, Pmax=0.0)
```
What output do you get?

**Comment by vdiky** [comment] 2019-04-11 05:34
VIS works for pures, but the return for that mixture is 300; 300; 0; 0 (T, T, D, P) which does not make sense. I use 10.0 release (Jun 2018)

**Comment by ianhbell** [comment] 2019-04-11 14:55
Please provide a runnable example like my Python one demonstrating the problem.  We need to know what exactly you did to get that behavior (what fluids you used, how you set up the fluids, etc.)

**Comment by EricLemmon** [comment] 2019-04-11 16:33
I believe this has already been fixed, can you try the new code up on my q drive in the install/1001 directory?

**Comment by vdiky** [comment] 2019-04-11 19:46
Results are still unstable and vary with time for R-125 + R-152a:

```cpp
strcpy(htyp, "VIS");
double z[20];
for (int i=0; i<20; i++) z[i] = 0;
z[0] = z[1] = 0.5;
LIMITSdll (htyp, z, t1, t2, d2, p2, 3);
```
Returned: sometimes 300, 300, 0, 0, sometimes 157, 500, 16, 60000 (approx.)
Always 0 for STN
Usually 0 for VIS called after STN and non-0 second time

**Comment by ianhbell** [comment] 2019-04-11 19:50
This example always returns the same thing for me: 
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\\Program Files (x86)\\REFPROP')
RP.SETPATHdll('D:\\Program Files (x86)\\REFPROP')
RP.SETFLUIDSdll('R125 * R152A')
z = [0.5, 0.5] + [0.0]*18
for counter in range(100):
    r = RP.LIMITSdll('VIS', z)
    print(r)
```
yields
```
LIMITSdlloutput(Tmin=300.0, Tmax=300.0, Dmax=0.0, Pmax=0.0)
LIMITSdlloutput(Tmin=300.0, Tmax=300.0, Dmax=0.0, Pmax=0.0)
LIMITSdlloutput(Tmin=300.0, Tmax=300.0, Dmax=0.0, Pmax=0.0)
...
```

Can you please provide a Short, Self Contained, Correct (Compilable), Example (http://sscce.org/) demonstrating your behavior?

**Comment by vdiky** [comment] 2019-04-11 20:48
That was my answer to Eric (about his dll 1001).
I can reproduce the problem in a short C++ function
```cpp
std::string refpropLoadError;
bool res = load_REFPROP(refpropLoadError, "./");
if (!res) return 1;
int ierr;
char HERR[errormessagelength + 1];
const int refpropfluidpathlength = 10000;
int ncomp = 2;
SETUPdll(ncomp, "3129.1.fld|5655.1.fld", "HMX.BNC", "DEF", ierr, HERR,
	refpropfluidpathlength, refpropcharlength,
lengthofreference, errormessagelength);
if (ierr) return 2;
char htyp[4];
strcpy(htyp, "VIS");
double z[20];
for (int i = 0; i < 20; i++) z[i] = 0;
z[0] = z[1] = 0.5;
double  t1, t2, d2, p2;
LIMITSdll(htyp, z, t1, t2, d2, p2, 3);
std::cout << t1 << '\t' << t2 << '\t' << d2 << '\t' << p2 << '\n';
```
consuming
```cpp
#include <windows.h>
#include <iostream>
#include <stdio.h>
#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION
```
Do you need the complete VS2017 solution?

**Comment by vdiky** [comment] 2019-04-11 20:52
Results:

VIS     300     300     0       0

TCX     157.521 500.169 15.9432 60000 

STN     1.00034 362.915 0       0

**Comment by ianhbell** [comment] 2019-04-11 20:52
A very confusing point for me is that now you are talking about new fluids, where before you were talking about R125 + R152a.  Do standard fluids cause failures?

I need a single C++ file that I can compile, so long as you have not fiddled with REFPROP_lib.h.

**Comment by vdiky** [comment] 2019-04-11 20:57
They are Refprop fld files for R125 and R152a extracted from the database. TDE does not keep the "guts outside" file layout and dynamically deploys fluid files from the database to a temporary folder for each TDE instance. I'll replace those files with generic Refprop files and upload the whole solution.

**Comment by ianhbell** [comment] 2019-04-11 20:58
Please don't upload the entire solution, rather just the C++ file that I can compile directly.

**Comment by vdiky** [comment] 2019-04-11 21:10
Note that function assumes availability of the generic Refprop files in the current folder.
[RefpropTests.zip](https://github.com/usnistgov/REFPROP-issues/files/3070615/RefpropTests.zip)

**Comment by ianhbell** [comment] 2019-04-11 21:42
I couldn't run this because the file REFPROPTests.h was missing, but commenting out that file, and adding an ``int main``, my example reads:
``` c++
#include <iostream>
#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION

int main()
{
    std::string refpropLoadError;
    bool res = load_REFPROP(refpropLoadError, "./"); 
    if (!res) return 1;
    int ierr;
    char HERR[errormessagelength + 1];
    const int refpropfluidpathlength = 10000;
    int ncomp = 2;
    SETUPdll(ncomp, "R125.fld|R152A.fld", "HMX.BNC", "DEF", ierr, HERR,
        refpropfluidpathlength, refpropcharlength,
        lengthofreference, errormessagelength);
    if (ierr) {
        std::cout << "fail\n";
        return 2;
    }
    char htyp[3][4] = { "STN", "VIS", "TCX" };
    double z[20];
    for (int i = 0; i < 20; i++) z[i] = 0;
    z[0] = z[1] = 0.5;
    double  t1, t2, d2, p2;
    for (int itype = 0; itype < 3; itype++)
    {
        LIMITSdll(htyp[itype], z, t1, t2, d2, p2, 3);
        std::cout << htyp[itype] << '\t' << t1 << '\t' << t2 << '\t' << d2 << '\t' << p2 << '\n';
    }
    return 0;
}

```
and the output is
```
STN     1.00034 362.915 0       0
VIS     300     300     0       0
TCX     157.521 500.169 15.9432 60000
```

**Comment by ianhbell** [comment] 2019-04-11 21:43
What do I have to do to get the irregular behavior you mention?

**Comment by vdiky** [comment] 2019-04-11 21:47
I would need to store a log of all Refprop calls that is not easy, unless logging capability is incorporated in Refprop.dll. As the problems are revealed by the above function, why not explore Refprop behavior there?

Hundreds of Refprop calls happen in TDE before Limits is called for a mixture.

**Comment by ianhbell** [comment] 2019-04-11 21:49
How do I need to modify your provided example to demonstrate the irregularity?

**Comment by vdiky** [comment] 2019-04-11 21:54
Got it!!!
```cpp
char htyp[][4] = { "STN", "VIS", "TCX", "VIS", "VIS", "VIS" };
for (int itype = 0; itype < sizeof(htyp)/sizeof(char*); itype++)
{
	LIMITSdll(htyp[itype], z, t1, t2, d2, p2, 3);
	std::cout << htyp[itype] << '\t' << t1 << '\t' << t2 << '\t' << d2 << '\t' << p2 << '\n';
}
```
```
STN     1.00034 362.915 0       0
VIS     300     300     0       0
TCX     157.521 500.169 15.9432 60000
VIS     157.521 500.169 15.9432 60000
VIS     157.521 500.169 15.9432 60000
VIS     157.521 500.169 15.9432 60000
```

**Comment by ianhbell** [comment] 2019-04-11 21:58
Confimed with:
``` C++
#include <iostream>
#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION

int main()
{
    std::string refpropLoadError;
    bool res = load_REFPROP(refpropLoadError, "./"); 
    if (!res) return 1;
    int ierr;
    char HERR[errormessagelength + 1];
    const int refpropfluidpathlength = 10000;
    int ncomp = 2;
    SETUPdll(ncomp, "R125.fld|R152A.fld", "HMX.BNC", "DEF", ierr, HERR,
        refpropfluidpathlength, refpropcharlength,
        lengthofreference, errormessagelength);
    if (ierr) {
        std::cout << "fail\n";
        return 2;
    }
    char htyp[6][4] = { "STN", "VIS", "TCX", "VIS", "VIS", "VIS" };
    double z[20];
    for (int i = 0; i < 20; i++) z[i] = 0;
    z[0] = z[1] = 0.5;
    double  t1, t2, d2, p2;
    for (int itype = 0; itype < 6; itype++)
    {
        LIMITSdll(htyp[itype], z, t1, t2, d2, p2, 3);
        std::cout << htyp[itype] << '\t' << t1 << '\t' << t2 << '\t' << d2 << '\t' << p2 << '\n';
    }
    return 0;
}
```

**Comment by EricLemmon** [comment] 2019-04-21 22:27
This is fixed now.  I changed the code to allow the string "VIS" to be sent in addition to "ETA".  I also changed the lower limit of the surface tension equations to match that of the lower temperature limit of the mixture model (the main model used to calculate thermodynamic properties).  The new code is up in the same place as usual.

**Closed as completed** 2019-04-29 15:07 UTC
Labels: bug, transport properties
