### ISSUE TITLE
Undefined behaviour regarding units with the REFPROP Excel add-in

### ISSUE THREAD

**Issue by pauliacomi** [usnistgov/REFPROP-issues#24] opened 2018-06-05 12:25 UTC
### Description

When using the Excel add-in I experience random switches between unit sets. When using the "Base SI" unit set, pressure results are reported sometimes in Pa and sometimes in bar. Density results are reported sometimes in mmol or sometimes in mol.

### Steps to Reproduce

1. Use the Excel add in to calculate gas density and pressure
2. Use the "Base SI" unit set
3. On subsequent opening of the workbook, output units sometimes change.
3. The behaviour is workbook dependent. If a workbook "switches" then all results calculated in that workbook are not respecting the unit set.

**Expected behavior:** Consistent calculation.

**Actual behavior:** What seems like random switching between unit sets.

### Versions

**REFPROP Version:** 9.4.4.19
**Operating System and Version:** Windows 10 Spring Creators Update  
**Access Method:** Excel

### Additional Information
I use macro enabled workbooks which have a the REFPROP VBA code embedded in them. Each workbook has a copy of the add-in.

Screenshot of two calculations which lead to results that are off by a factor of 1e3. The inputs are identical or near-identical.

![2018-06-05_li](https://user-images.githubusercontent.com/9705355/40975304-c3625e68-68ca-11e8-82b9-73fda4be690b.jpg)

**Comment by ianhbell** [comment] 2018-06-05 15:05
Thanks for the report - we will investigate ASAP

**Comment by ianhbell** [comment] 2018-06-07 16:03
Thank you for the excellent bug report - very clear!!

I have a strong suspicion that the problem is because you have two copies of the addin code, one in each worksheet.  Please see the instructions here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel .  You should have one copy of the addin, and each workbook should be using the same addin.  I think the same DLL is loaded in each instance, and the Excel one is not handshaking correctly because each addin thinks that it owns the DLL instance and handles the state inappropriately.

**Comment by ianhbell** [comment] 2018-06-08 15:38
The word from Eric is that this is likely a version of the beta that is too old.  Can you please update your beta and try again?

**Comment by pauliacomi** [comment] 2018-06-08 16:01
Hi Ian, thanks for the explanations - I didn't realise that the VBA code duplication could be an issue. I suspected it might play a role since I've seen odd behaviour before when having two workbooks open at the same time, like the functions would return random data.

In this case however, I thought to be a separate issue since the behaviour was present even with a single notebook on open/close and with a very clear pattern.

I'll first update to the newest beta then and I'll try to work with REFPROP only as an add-in. I'll let you know if the issue persists.

**Comment by ianhbell** [comment] 2018-06-08 16:07
I’m not sure that *is* the issue, but I think it can’t hurt to try to isolate the problem prior to digging into debugging REFPROP.

**Comment by pauliacomi** [comment] 2018-06-15 14:37
Hi Ian, thanks for the explanations - I didn't realise that the VBA code duplication could be an issue. I suspected it might play a role since I've seen odd behaviour before when having two workbooks open at the same time, like the functions would return random data. In this case however, I thought to be a separate issue since the behaviour was present even with a single notebook on open/close and with a very clear pattern.

After the update to the newest beta then and using REFPROP as an add-in for a while I haven't seen any more problems.

**Comment by ianhbell** [comment] 2018-06-18 20:30
If this is fixed, please go ahead and close the issue.

**Closed** 2018-06-18 20:39 UTC
