### ISSUE TITLE
Handle Leak in Refprop 10

### ISSUE THREAD

**Issue by tkordts** [usnistgov/REFPROP-issues#299] opened 2020-05-26 07:50 UTC
I think I found a handle leak in Refprop 10. We are using Refprop in our software for climate formulas and diagrams. Originally, I discovered the behavior in our software But it can also be reproduced with the C# wrapper, Excel document and the Refprop.exe from the installation.
In our software it was noticed that when a climate diagram was created, our software had over 10000 open handles at once. Each time the fluid was changed, there were about 10000 handles open again. With Refprop 9.1 this problem did not occur. There the number of handles remained very low.
Since we use our own wrapper, I used the C# wrapper from github and wrote a simple unit test for it. In the unit test only the IRefProp64.SETUPdll and afterwards 100 times the method IRefProp64.SATPdll is called. On my computer the number of handles increases by 2 with each call. If the same unit test is started with the Refprop 9.1 Dll, the number of handles remains constant. 
Since the Handle Leak also occurs with Refprop.exe, I describe the behavior for it.

A tool to display the handles in Windows can be found here: https://docs.microsoft.com/en-us/sysinternals/downloads/handle
Also here is a small guide to displaying handles https://blogs.technet.microsoft.com/yongrhee/2011/12/19/how-to-troubleshoot-a-handle-leak/
In the Steps to Reproduce guide I use the handle tool from the first link.

### Steps to Reproduce

1). Start REFPROP.EXE
2.) Plot -> Select "p-h diagram" -> Confirm dialog with OK.
3.) Open command line as administrator and change to the directory of Handle.exe.
4.) Enter the command "handle -s -p refprop.exe For me Refprop.exe has about 700 handles
5.) In Refprop select "Substance" -> "Pure Fluid" -> "Argon" and confirm dialog with OK.
6.) Plot -> Select "p-h diagram" -> Confirm dialog with OK.
7.) Execute the command "handle -s -p refprop.exe" again. On my system Refprop.exe has about 825 handles
8.) Select "Substance" -> "Pure Fluid" -> "Oxygen" in the refprop and confirm the dialog with OK.
9.) Plot -> Select "p-h diagram" -> Confirm dialog with OK.
10.) Execute the command "handle -s -p refprop.exe" again. In my case Refprop.exe has about 1300 handles
11.)With every further change of the fluid and drawing a diagram the number of handles increases by a few hundred.
In the Handle.exe tool, the number of "mutant" handles increases with each pass. These are mutex objects.

If the steps are done with Refprop.exe from Refprop 9.1, the number of handles increases by 4 between step 4 and step 10.

Of course the path described is not yet dangerous. But in our software it sometimes happens that a customer generates 10 or 20 climate diagrams.  While with Refprop 9.1 the number of handles was then below 1000, now with Refprop 10 the number of handles is 200,000 (with 20 diagrams). Since our software was still designed for Refprop 9 and older, we still use the legacy API of Refprop 10. I haven't done a test with the new API yet, but since the behavior already occurs with Refprop.exe I assume that it might be a general problem?
It can also be reproduced with the Excel document. If I change a fluid there and the Excel document is recalculated, the number of handles increases more and more.

If you need more information, I can provide it.

### Versions

**REFPROP Version: Refprop 10
**Operating System and Version: Windows 10 64 Bit (10.0.18362)

Refprop 9.1 After Step 10
![refprop9 1](https://user-images.githubusercontent.com/31503819/82873114-4f8d5680-9f34-11ea-8925-554da060b25c.png)

Refprop 10 After Step 10
![refprop10](https://user-images.githubusercontent.com/31503819/82873143-5ae08200-9f34-11ea-9b13-573084e72ed5.png)

Our software with Refprop 9.1 and 20 climate diagrams
![softwareRefprop9 1](https://user-images.githubusercontent.com/31503819/82874328-135af580-9f36-11ea-8d71-b6b5dcf04672.png)

Our software with Refprop 10 and 20 climate diagrams
![softwareRefprop10](https://user-images.githubusercontent.com/31503819/82874335-1655e600-9f36-11ea-8212-8f8fc33c5fd1.png)

**Comment by ianhbell** [comment] 2020-05-26 12:57
Can you reproduce this with a simple C++ code? Or provide an excel spreadsheet with only one or two cells so that we have some prayer of narrowing down the bug? Otherwise its a needle in a haystack.

**Comment by tkordts** [comment] 2020-05-27 09:34
I made a little more progress in the search today. The handle leak seems to occur every time a method from the Refprop Api returns an error code greater than 0. In Refprop 9.1 the handle leak does not occur, even if an error code is returned.
I am not a C++ programmer. If the example is not optimal and some places could be programmed better, I apologize. The code has become a bit long due to the whole initialization. The important part is at the end.
The value 0 is passed for the pressure and the method returns with error code 141. If I pass the value 1 for the pressure, I get the error code 0 and the leak does not occur in Refprop 10.
Also an output with Refprop 9.1 and 10.
While in Reprop 10 the number of handles increases with each call, the value in reprop 9.1 remains constant.
The program makes limited sense, because it does nothing else but constantly provoke an error code. But as you saw in the post yesterday, the Refprop.exe, the Excel file and our own software seem to generate some error codes during the calculations. And with each error code, further handles are not closed correctly.

``` c++
#include "stdafx.h"
#include <string>
#include <Windows.h>
#include <iostream>

using namespace std;
typedef void(__stdcall *fp_SETUPdllTYPE)(long&, char*, char*, char*, long&, char*, long, long, long, long);
typedef void(__stdcall *fp_SATPdllTYPE)(double&, double*, long&, double&, double&, double&, double*, double*, long&, char*, long);

int main()
{
	HINSTANCE hRefpropDllInstance = LoadLibrary(L"C:\\Program Files (x86)\\Refprop\\REFPRP64.DLL");
	fp_SETUPdllTYPE pfnSETUPdll = (fp_SETUPdllTYPE)GetProcAddress(hRefpropDllInstance, "SETUPdll");
	fp_SATPdllTYPE  pfnSATPdll = (fp_SATPdllTYPE)GetProcAddress(hRefpropDllInstance, "SATPdll");
	HANDLE hHandle = GetCurrentProcess();
	DWORD pdwHandleCount;
	if (pfnSATPdll == NULL || pfnSETUPdll == NULL)
		return E_FAIL;
	long index, lNumberOfComps, lLastErrorCode = 1;
	char szReference[] = "DEF";
	char szLastErrorMsg[256];
	double dPressure, dTemperatureLiquid, liquidDensity, vaporDensity = 0.0;
	double dComponent[20], xliq[20], xvap[20] = { 0.0 };
	string stFluidFilePath = R"(C:\Program Files (x86)\Refprop\FLUIDS\r134a.fld)";
	char* szFluidFilePath = const_cast<char*>(stFluidFilePath.c_str());
	string stMixtureFilePath = R"(C:\Program Files (x86)\Refprop\FLUIDS\HMX.BNC)";
	char* szMixtureFilePath = const_cast<char*>(stMixtureFilePath.c_str());
	pfnSETUPdll(lNumberOfComps, szFluidFilePath, szMixtureFilePath, szReference, lLastErrorCode, szLastErrorMsg, 10000, 255, 3, 255);
	GetProcessHandleCount(hHandle, &pdwHandleCount);
	cout << "HandleCount before SATPdll: " << pdwHandleCount << endl;
	for (int i = 0; i < 25; i++)
	{
		pfnSATPdll(dPressure, dComponent, index, dTemperatureLiquid, liquidDensity, vaporDensity, xliq, xvap, lLastErrorCode, szLastErrorMsg, 255);
		GetProcessHandleCount(hHandle, &pdwHandleCount);
		cout << "HandleCount after call " << i+1 <<" of SATPdll: " << pdwHandleCount << " ErrorCode: "<< lLastErrorCode<< endl;
	}
	system("pause");
	return 0;
}
```

Test program with Refprop 9.1
![HandleCountRefProp9 1](https://user-images.githubusercontent.com/31503819/83002042-d9105780-a00c-11ea-88d2-4d1373e25014.png)
Test program with Refprop 10
![HandleCountRefProp10](https://user-images.githubusercontent.com/31503819/83006698-e8929f00-a012-11ea-9a86-fa7915a175bb.png)

**Comment by EricLemmon** [comment] 2020-05-27 10:32
It's been a very long time since I compiled the code for 9.1, but for many years we used the Lahey compiler for all of our Fortran work, and at some point switched over to the Intel compiler.  If indeed this is true, it might be possible to recompile version 10 with the Lahey code (assuming I can find all the pieces needed to do that) to see if it is compiler dependent.  Or perhaps some other compiler could also be used?

This might also have been fixed over the last two years since version 10 was released.  If you would like to try the current beta, please let me know (eric.lemmon@nist.gov).

**Comment by ianhbell** [comment] 2020-05-27 12:38
Nice work with this report, very clear example.  Do you know (in general) what sorts of things cause handles to be allocated in FORTRAN? We certainly do not do any manual handle allocation within the code.

Also, you have some issues with string buffer sizes (FORTRAN wants fixed length strings, not null-terminated ones), but I don't think that is related to the handle issue.

**Comment by tkordts** [comment] 2020-05-27 13:49
What I had found out was that they were so-called "mutant" handles. I can't see where they came from. According to google, they are mutex objecte not cleaned up. 
This one sounds a bit like the error https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/806603

![mutant-handle](https://user-images.githubusercontent.com/31503819/83025720-5baa0e80-a02f-11ea-8861-606bd266fbc7.png)

**Comment by ianhbell** [comment] 2020-05-27 15:06
Definitely never seen this before...  but also didn't go looking for it.  Does linux have a similar notion?  If so, I could run your example with gfortran on linux,  Perhaps this is just an issue in Intel Fortran?  Did you use the same compiler for both 9.1 and 10?

**Comment by tkordts** [comment] 2020-05-28 05:44
I worked with Visual Studio on Windows. My program was compiled once with the path for Reprop 9.1 and once with the path for Refprop 10.
I don't work professionally with C++ or Linux but the example uses commands from the Windows API e.g. to determine the open handles or to do the DLL import. These commands all need to be ported to Linux.

**Comment by ianhbell** [comment] 2020-05-28 12:53
I see, so you didn't compile REFPROP yourself, but it could still be a question of which Intel Fortran compiler was used to compile 9.1 and 10 if they differ.  I can use the same one to identify whether the issue is caused by the compiler.

**Comment by ianhbell** [comment] 2020-05-28 22:43
On my side with windows 10, with visual studio, I fixed the call to SETUPdll (no longer fails with ierr = 109), and now, I cannot reproduce your error:
```c++
#include <string>
#include <Windows.h>
#include <iostream>

using namespace std;
typedef void(__stdcall* fp_SETUPdllTYPE)(long&, char*, char*, char*, long&, char*, long, long, long, long);
typedef void(__stdcall* fp_SATPdllTYPE)(double&, double*, long&, double&, double&, double&, double*, double*, long&, char*, long);

int main()
{
    HINSTANCE hRefpropDllInstance = LoadLibrary("D:\\Program Files (x86)\\Refprop\\REFPRP64.DLL");
    fp_SETUPdllTYPE pfnSETUPdll = (fp_SETUPdllTYPE)GetProcAddress(hRefpropDllInstance, "SETUPdll");
    fp_SATPdllTYPE  pfnSATPdll = (fp_SATPdllTYPE)GetProcAddress(hRefpropDllInstance, "SATPdll");
    HANDLE hHandle = GetCurrentProcess();
    DWORD pdwHandleCount;
    if (pfnSATPdll == NULL || pfnSETUPdll == NULL)
        return E_FAIL;
    long index, lNumberOfComps=1, lLastErrorCode = 1;
    char szReference[] = "DEF";
    char szLastErrorMsg[256];
    double dPressure, dTemperatureLiquid, liquidDensity, vaporDensity = 0.0;
    double dComponent[20], xliq[20], xvap[20] = { 0.0 };
    string stFluidFilePath = R"(D:\Program Files (x86)\Refprop\FLUIDS\r134a.fld)";
    char* szFluidFilePath = const_cast<char*>(stFluidFilePath.c_str());
    string stMixtureFilePath = R"(D:\Program Files (x86)\Refprop\FLUIDS\HMX.BNC)";
    char* szMixtureFilePath = const_cast<char*>(stMixtureFilePath.c_str());
    pfnSETUPdll(lNumberOfComps, szFluidFilePath, szMixtureFilePath, szReference, lLastErrorCode, szLastErrorMsg, 10000, 255, 3, 255);
    cout << "ierr: " << lLastErrorCode << std::endl;
    cout << "herr: " << szLastErrorMsg << std::endl;
    GetProcessHandleCount(hHandle, &pdwHandleCount);
    cout << "HandleCount before SATPdll: " << pdwHandleCount << endl;
    for (int i = 0; i < 25; i++)
    {
        pfnSATPdll(dPressure, dComponent, index, dTemperatureLiquid, liquidDensity, vaporDensity, xliq, xvap, lLastErrorCode, szLastErrorMsg, 255);
        GetProcessHandleCount(hHandle, &pdwHandleCount);
        cout << "HandleCount after call " << i + 1 << " of SATPdll: " << pdwHandleCount << " ErrorCode: " << lLastErrorCode << endl;
    }
    system("pause");
    return 0;
}
```
yielding
```
ierr: 0
herr:                                                                                                                                                                                                                                           
HandleCount before SATPdll: 32
HandleCount after call 1 of SATPdll: 32 ErrorCode: 141
HandleCount after call 2 of SATPdll: 32 ErrorCode: 141
HandleCount after call 3 of SATPdll: 32 ErrorCode: 141
HandleCount after call 4 of SATPdll: 32 ErrorCode: 141
HandleCount after call 5 of SATPdll: 32 ErrorCode: 141
HandleCount after call 6 of SATPdll: 32 ErrorCode: 141
HandleCount after call 7 of SATPdll: 32 ErrorCode: 141
HandleCount after call 8 of SATPdll: 32 ErrorCode: 141
HandleCount after call 9 of SATPdll: 32 ErrorCode: 141
HandleCount after call 10 of SATPdll: 32 ErrorCode: 141
HandleCount after call 11 of SATPdll: 32 ErrorCode: 141
HandleCount after call 12 of SATPdll: 32 ErrorCode: 141
HandleCount after call 13 of SATPdll: 32 ErrorCode: 141
HandleCount after call 14 of SATPdll: 32 ErrorCode: 141
HandleCount after call 15 of SATPdll: 32 ErrorCode: 141
HandleCount after call 16 of SATPdll: 32 ErrorCode: 141
HandleCount after call 17 of SATPdll: 32 ErrorCode: 141
HandleCount after call 18 of SATPdll: 32 ErrorCode: 141
HandleCount after call 19 of SATPdll: 32 ErrorCode: 141
HandleCount after call 20 of SATPdll: 32 ErrorCode: 141
HandleCount after call 21 of SATPdll: 32 ErrorCode: 141
HandleCount after call 22 of SATPdll: 32 ErrorCode: 141
HandleCount after call 23 of SATPdll: 32 ErrorCode: 141
HandleCount after call 24 of SATPdll: 32 ErrorCode: 141
HandleCount after call 25 of SATPdll: 32 ErrorCode: 141
```

**Comment by ianhbell** [comment] 2020-05-28 22:45
P.S. There is still a bug in your code with regards to the input strings which should be padded for utmost safety.  

N.B.: I used version 10.0.0.2 of REFPROP for my tests.

**Comment by tkordts** [comment] 2020-05-29 07:06
We do not compile Refprop ourselves. We bought it and use the installer that was provided to us (NIST2310.EXE). We do not ship our software with Refprop. If a customer wants to use the climate function, he has to buy reprop separately.

I can only emphasize again that I do not work with C++. I derived the C++ code from my C# unit test.  I cannot remove the "L"" at LoadLibrary. I just assume that the project is set up differently.  I guess, because I am in Germany and my project is set to Unicode, I have to pass the path as unicode string.

In my C# unit test I corrected the string to the correct length. I still get 2 additional handles with every call. And only in Refprop 10.
Refprop 10 Test strings with correct length 
```
iErr: 141 HandleCount: 442
iErr: 141 HandleCount: 444
iErr: 141 HandleCount: 446
iErr: 141 HandleCount: 448
iErr: 141 HandleCount: 450
iErr: 141 HandleCount: 452
iErr: 141 HandleCount: 454
iErr: 141 HandleCount: 456
iErr: 141 HandleCount: 458
iErr: 141 HandleCount: 460
iErr: 141 HandleCount: 462
iErr: 141 HandleCount: 464
iErr: 141 HandleCount: 466
iErr: 141 HandleCount: 468
iErr: 141 HandleCount: 470
iErr: 141 HandleCount: 472
iErr: 141 HandleCount: 474
iErr: 141 HandleCount: 476
iErr: 141 HandleCount: 478
iErr: 141 HandleCount: 480
iErr: 141 HandleCount: 482
iErr: 141 HandleCount: 484
iErr: 141 HandleCount: 486
iErr: 141 HandleCount: 488
iErr: 141 HandleCount: 490
```
It can also be reproduced with the test project from the C# wrapper from the REFPROP-wrappers project. Press the "Calc" button once and with Refprop 10 there are 5500 open handles.  With Refprop 9.1 there are only 300. In the test project the strings are all in the right length. I don't think this is the cause. The error can be reproduced with Refprop.exe and REFPROP.XLS.

It was suggested to me, I can try this with a beta. Unfortunately there was an answer that he is on vacation. How can I try the 10.0.0.2? If you can provide me the dll for testing, I can try it on my PC. 
Can you also try the test with the version that comes with the setup?

**Comment by tkordts** [comment] 2020-05-29 11:13
I can verify what you say. I downloaded a demo version of the Intel Fortran Compiler (2018 Update 4) and built the Refprop.dll myself (https://github.com/usnistgov/REFPROP-cmake). The handle leak does not occur with this dll. Then it only affects the Refprop.dll from the NIST2310.EXE setup.

**Comment by ianhbell** [comment] 2020-05-29 11:48
Please email me at ian.bell@nist.gov and I can send you the links for 10.0.0.2

**Comment by ianhbell** [comment] 2020-05-29 12:13
Also, the link you sent sounds exactly like the issue we are having.

**Comment by tkordts** [comment] 2020-05-30 08:10
It's okay with me for now. With the self-built version it does not occur. So I don't need the beta or the compiled DLL anymore. But thanks for the offer. This sounds like the suspicion that the Fortran compiler is responsible for the leak.

**Comment by ianhbell** [comment] 2020-06-03 19:50
Can we close this issue then?

**Closed as completed** 2020-06-04 05:37 UTC
Labels: Fortran code
