### ISSUE TITLE
Predefined Mixture Run-time error '62'

### ISSUE THREAD

**Issue by JunelElla** [usnistgov/REFPROP-issues#233] opened 2019-12-19 21:53 UTC
### Description

Predefined Mixture Run-time error '62':
Input past end of file

### Steps to Reproduce

1. Launch REFPROP
2. Click on Substance
3. Select Predefined Mixture

**Expected behavior:** [What you expect to happen]

No error message.  Predefined Mixture should show up a list of built-in multicomponent refrigerants.

**Actual behavior:** [What actually happens]

NIST23 pop up window appears with the following error message
Predefined Mixture Run-time error '62':
Input past end of file

Pressing OK, closes REFPROP program

### Versions

**REFPROP Version:** [REFPROP version you are using]  REFPROP 10.0.a
**Operating System and Version:** [OS you are running REFPROP on]  Windows 10 Pro
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/59068552/71212683-e9a5fe80-2305-11ea-9f53-59598d56483e.png)

**Comment by EricLemmon** [comment] 2019-12-23 11:40
There is a file called Fld_Info.lst in your Refprop directory.  Delete that file and see if the problem is gone.  If not, look in the Refprop\Mixtures directory and see if it contains about 120 *.mix files.  If it does, open up one of these with notepad.  It should look something like the following:

```R401A    [R-22/152a/124 (53/13/34)]
 94.43842620976127 380.89613442148936 4641.440488043944 5.238865109277451
 3
R22.FLD
R152A.FLD
R124.FLD
 .578854210704231
 .185871453986601
 .235274335309169
 0
```

If these don't work, let us know!

**Comment by JunelElla** [comment] 2019-12-24 00:26
Thanks Eric.  I deleted Fld_Info.lst and restarted my PC but I am still having the same error.
I can confirm that I have 121 *.mix files which has similar syntax in your post.

**Comment by EricLemmon** [comment] 2019-12-24 00:51
Can you take a screen shot of your Refprop directory so that I can see what's in it?  It should look like mine below with the same dates and file sizes.  If they do look like mine, perhaps I can log into your machine and try it directly?  If that's possible, please email me at eric.lemmon@nist.gov.

![image](https://user-images.githubusercontent.com/42392984/71386601-3874c200-25ac-11ea-909a-347cffe9272b.png)

![image](https://user-images.githubusercontent.com/42392984/71386642-71ad3200-25ac-11ea-95cb-9f272238d870.png)

![image](https://user-images.githubusercontent.com/42392984/71386668-90abc400-25ac-11ea-9a80-8f4fb0405028.png)

**Comment by EricLemmon** [comment] 2020-01-21 18:20
I see that this post is about a month old now, can you remind me if we were able to solve this issue?  If not, is it still a problem?  If solved, can you close the issue?

**Comment by JunelElla** [comment] 2020-01-21 21:37
Hi Eric,

Thank you for bumping this up.

I sent you my reply to your nist.gov email.  Please respond if you got it.


Kind Regards,



Junel Ella
Process Engineer
A-Gas Australia
9-11 Oxford Road
Laverton North,VIC,3026
P: 
+61 3 9368 9207
F: +61 (0) 3 9368 9233
junel.ella@agas.com
www.agas.com
A-GAS AU11734

**Comment by EricLemmon** [comment] 2020-05-27 00:46
This issue has been resolved.  There were several hidden files outside of the Refprop directory.  Once they were removed then the program worked well.

**Closed as completed by EricLemmon** 2020-05-27 00:46 UTC
Labels: GUI
