### ISSUE TITLE
Unable to calculate properties - issue of blank spaces in the REFPROP UI.

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#89] opened 2019-01-22 08:42 UTC
### Description
Unable to calculate properties - issue of blank spaces in the REFPROP UI.

[Description of the issue]
Test Case 1: 3_NC16_NC22_12CE.rfp vs 3_diff_order.rfp
Component Orders:  Docosane/Hexadecane/Dichloroethane: Specified state points (0.33333/0.33333/0.33333) VS Docosane/Dichloroethane/Hexadecane: Specified state points (0.33333/0.33333/0.33333)
Observations: 1) Different Component Orders missing values
2) Machine dependent results

### Steps to Reproduce

1. [First Step]
Define a new mixture with these components--> Docosane/Dichloroethane/Hexadecane
2. [Second Step]
Specificy composition (0.33333/0.33333/0.33333) , with default equation of state i.e., NIST23
3. Specify state points: Temperature=300 K, Pressure = 300.0 Kpa

**Expected behavior:** [What you expect to happen]
Able to display calculated property values without blank spaces.

**Actual behavior:** [What actually happens]
Observations: 1) Different Component Orders missing values
2) Machine dependent results

### Versions

**REFPROP Version:** [10.0.0.02]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Direct Standalone application]  

Additional Information
Please refer to the attached zip file [2_Blank_spaces_between.zip](https://github.com/usnistgov/REFPROP-issues/files/2781927/2_Blank_spaces_between.zip)
 where in attached the REFPROP input, output result files.

**Comment by EricLemmon** [comment] 2019-03-30 04:08
I am unable to reproduce this issue, but believe it is related to #88.  It is quite possible that some old bug fixes have fixed this problem.  

I will close this issue and report all subsequent findings in issue 88 to keep things together.  Once you have obtained a new DLL, if you find the issue is still there, please feel free to open this issue back up.

**Closed as completed by EricLemmon** 2019-03-30 04:08 UTC
Labels: GUI

**Comment by msuresh20** [comment] 2019-03-30 05:31
Thanks for fixing the issue.

If possible can I get the latest REFPROP.dll to test this.

**Comment by msuresh20** [comment] 2019-05-23 10:20
After using the latest REFPROP.DLL (v10.0.0.66), validated the issue. 
The issue was resolved.

Thanks for fixing the issue.
